# Generated by Django 5.1.6 on 2025-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_requests_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='data_from_api',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
