# Generated by Django 5.1.6 on 2025-03-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request_data_from_api'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requests_data',
        ),
    ]
