# Generated by Django 5.1.6 on 2025-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='#post', max_length=180),
            preserve_default=False,
        ),
    ]
