# Generated by Django 5.1.6 on 2025-03-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
